[package]
name = "toml-cbombadil"
version = "0.1.0"
authors = ["Paul Delafosse <paul.delafosse@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "^0"
dirs = "^3"
toml = "^0"
serde_yaml = "0.8"
serde_derive = "^1"
serde = "^1"
pest = "^2"
pest_derive = "^2"
anyhow = "^1"

[dev-dependencies]
temp_testdir = "0.2"