[theme] 
red = "#ff3333" 
black = "#000033"
green = "#66ff66"

  [theme.alacritty]
  source = "alacritty/alacritty.yml"

  [theme.sway] 
  source = "sway/colors"

  [theme.wofi]
  source = "wofi/style.css"


[[dot]]
source = "alacritty"
target = "alacritty"

[[dot]]
source = "wofi"
target = ".config/wofi"

[[dot]]
source = "sway"
target = ".config/sway"
