dotfiles_dir = "dotfiles"

[[hook]]
command = "sway reload"

[[var]]
path = "vars.toml"

[[dot]]
source = "alacritty"
target = ".config/alacritty/alacritty.yml"

[[dot]]
source = "wofi"
target = ".config/wofi"

[[dot]]
source = "sway"
target = ".config/sway"

#[xdg]
#web_browser = "firefox-developper-edition"
#mail = "thunderbird"
#image.jpeg = "eog"


